apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: cloudbox
  annotations:
    # Replace with: terraform output -raw backend_irsa_role_arn
    eks.amazonaws.com/role-arn: "arn:aws:iam::061640054424:role/cloudbox-prod-backend-role"
