global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    cluster: dropbox-local

scrape_configs:
  - job_name: backend
    static_configs:
      - targets: ['backend:4000']
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
